include:
  # $CI_PROJECT_PATH can be used as the project on GitLab.com but not yet on a local GitLab install
  # https://gitlab.com/gitlab-org/gitlab/-/issues/30686#note_477681811
  - project: 'shell-bootstrap-scripts/shell-bootstrap-scripts'
    file: 'before_script.yaml'
    ref: master
  - project: 'shell-bootstrap-scripts/shell-bootstrap-scripts'
    file: 'build_with_kaniko.yaml'
    ref: master

build_for_gitlab_project_registry:
  extends: .build_with_kaniko
  stage: build
  variables:
    SKIP_DOCKER_TAG_COMMIT_SHORT_SHA: 1


test-debian:
  stage: test
  image: $CI_REGISTRY_IMAGE/debian
  script:
  - apt-get install --assume-yes python3-pip

